### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by timotheecour** [dart-lang/sample-pop_pop_win#50]
am i missing something?

```
git clone https://github.com/dart-lang/sample-pop_pop_win

open in webstorm

run index.html

open developper mode in Chromium: shows:
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:xxxxx/sample-pop_pop_win/web/packages/pop_pop_win/assets/style.css 
```

**Comment by kevmoo** [comment]
Make sure you run 'pub get'

In webstorm, open a dart file in web/ or lib/

You should see a notification about 'enable Dart support'. Do that.

Then run 'pub get'

Let me know if that works!

**Comment by timotheecour** [comment]
that worked thanks!
one more thing:

* despite it working i am getting error: A value of type 'DisplayObjectParent<DisplayObject>' can't be assigned to a variable of type 'BoardElement'. (invalid_assignment at [pop_pop_win] lib/src/stage/square_element.dart:105)

* is this the right way to run command line (without IDE)?
```
pub build
cd build
python -m SimpleHTTPServer 8000
browse http://localhost:8000/
```

**Comment by kevmoo** [comment]
`pub serve` is easier

Could you copy-paste the context of the error? Is this from pub build or
within the browser?

Which browser are you using?
Which version of the SDK?

**Comment by timotheecour** [comment]
that error was from webstorm IDE.

thanks for `pub serve` command (works from chromium)

dart SDK 1.24.2 (via homebrew)

**Comment by kevmoo** [comment]
A good place for general Q&A is https://gitter.im/dart-lang/TALK-general

Or ask questions here: https://stackoverflow.com/tags/dart/

Glad you got it working!
