### ISSUE TITLE
Need Dart-2 to use.. Dart Update keeps @ 1.24.3

### ISSUE THREAD

**Issue by doctormellow** [dart-lang/sample-pop_pop_win#57]
So "Dart 2" is still landing, I've scoured the site link to install Dart 2
https://www.dartlang.org/dart-2

but there is nothing mentioned of downloading, I've installed the Dart SDK and ran Dart Update, but it stated that I'm at the latest version at 1.24.3, how the hell do I get a hold of Dart 2?

**Comment by matanlurey** [comment]
Hi @doctormellow.

Sorry you found the documentation confusing. You'll want to use the [`dev channel`](https://www.dartlang.org/install#about-sdk-release-channels-and-version-strings), which is between a daily and weekly release, and a little less stable as a result, but tracks Dart 2 (we are on `2.0.0-dev.35.0` as of today).

Please also be respectful and mindful of our [code of conduct](https://www.dartlang.org/code-of-conduct) when filing issues. I understand your frustration, but please watch your language. Thanks!

**Comment by doctormellow** [comment]
my apologies, thanks for the quick response
