### ISSUE TITLE
build_runner 0.4.0 dep breaks sample

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/sample-pop_pop_win#58]
Hey @kevmoo, 

As of 0.4.0, build_runner sets `ignore_cast_failures` to false by default, resulting in runtime errors whenever StageXL fires Events. You can witness this when running this project, for example.

For a quick fix, see https://github.com/nilsdoehring/dartbook/blob/master/build.yaml#L12 how to set the flag to true (I had to unearth that info from build_runner sources).

But, of course we don't want StageXL to produce cast errors in the first place. Unfortunately, neither @bp74 nor I understand why it does. Much appreciated if you could join our [discussion](https://groups.google.com/forum/#!topic/stagexl/Jke-igqZMFQ).

Thanks!

**Comment by kevmoo** [comment]
Seems like a bug in DDC. Not PPW. Something with `EventTovoid()._check(subscription.eventListener)`

**Comment by kevmoo** [comment]
CC @jmesserly – thoughts?

**Comment by jmesserly** [comment]
I think this was fixed in https://github.com/bp74/StageXL/pull/310 ?

**Comment by kevmoo** [comment]
Yup. Thanks!

**Comment by nilsdoehring** [comment]
Sorry, forgot to close this earlier. The root cause was super hard to identify, by the way. Will browser debugging and/or error messages improve before Dart 2 hits stable?

e.g. this was the original error (WS 2018.1.3 EAP, SDK 2.0.0-dev54.0). It did not 'produce' a breakpoint in debugger (don't know the correct lingo here).
<img width="1420" alt="bildschirmfoto 2018-05-12 um 18 47 18" src="https://user-images.githubusercontent.com/1327275/39964571-4aaae4a4-5687-11e8-87ec-44e36e37ec39.png">

**Comment by kevmoo** [comment]
totally agree, @nilsdoehring – @jmesserly @vsmenon @alan-knight  – FYI

...we have done a lot of work to make these types of errors better. But more examples are certainly helpful!

**Comment by jmesserly** [comment]
Do you know what's printing `Uncaught _hs_helper.TypeErrorImplementation`? Is that JS code or is it Dart code?

I wonder if we have a bug where Dart toString isn't hooked up to JS toString.

**Comment by nilsdoehring** [comment]
JS, here's Chrome's console output:
![image](https://user-images.githubusercontent.com/1327275/40028813-35025f78-57e1-11e8-86f0-b9e84425b88c.png)

**Comment by nilsdoehring** [comment]
@jmesserly may I point you to [this](https://github.com/nilsdoehring/StageXL_DragonBones/issues/1), where I put together a more elaborate description of the debugging experience.
