### ISSUE TITLE
Source file for art?

### ISSUE THREAD

**Issue by gianghl1983** [dart-lang/sample-pop_pop_win#83]
Hi,
Can you please share source file for game assets? (PSD/SVG...) or if not can you please split assets to single picture (dart_opaque_01).
Br,

**Comment by kevmoo** [comment]
Uh...I don't think so. Look through the source history maybe?

**Comment by gianghl1983** [comment]
Sorry, I could not file the source anywhere..

**Comment by kevmoo** [comment]
The project is over 10 years old. They may be lost to history!

**Comment by gianghl1983** [comment]
I see! Thanks anyway!
